[package]
name = "ff"
version = "0.1.0"
authors = ["Congee <congeec@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
